export const Tokens = [
  {
    name: "EUROe",
    mintAddress: "2VhjJ9WxaGC3EZFwJG9BDUs9KxKCAjQY4vgd1qxgYWVg",
    decimals: 6,
    image: "/assets/svg/stablecoins/euroe.svg",
    status: "available",
  },
  {
    name: "QCAD",
    decimals: 2,
    mintAddress: "EeBX9JLdvsp4HnBbMgC1HnAjBkBQxgxtWxspcCLtT6ci",
    image: "/assets/svg/stablecoins/qcad.svg",
    status: "available",
  },
  {
    name: "USDC",
    mintAddress: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
    decimals: 6,
    image: "/assets/svg/stablecoins/usdc.svg",
    status: "available",
  },
  {
    name: "USDY",
    mintAddress: "A1KLoBrKBde8Ty9qtNQUtq3C2ortoC3u7twggz7sEto6",
    decimals: 6,
    image: "/assets/svg/stablecoins/usdy.svg",
    status: "available",
  },
  {
    name: "USDT",
    mintAddress: "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB",
    decimals: 6,
    image: "/assets/svg/stablecoins/usdt.svg",
    status: "available",
  },
  {
    name: "PYUSD",
    mintAddress: "2b1kV6DkPAnxd5ixfnxCpjxmKwqjjaYmCZfHsFu24GXo",
    decimals: 6,
    image: "/assets/svg/stablecoins/pyusd.svg",
    status: "available",
  },
  {
    name: "BRZ",
    mintAddress: "FtgGSFADXBtroxq8VCausXRr2of47QBf5AS1NtZCu4GD",
    decimals: 4,
    image: "/assets/svg/stablecoins/brz.svg",
    status: "available",
  },
  {
    name: "EURC",
    mintAddress: "HzwqbKZw8HxMN6bF2yFZNrht3c2iXXzpKcFu7uBEDKtr",
    decimals: 6,
    image: "/assets/svg/stablecoins/eurc.svg",
    status: "unavailable",
  },
  {
    name: "TRYB",
    mintAddress: "6ry4WBDvAwAnrYJVv6MCog4J8zx6S3cPgSqnTsDZ73AR",
    decimals: 6,
    image: "/assets/svg/stablecoins/tryb.svg",
  },
  {
    name: "ISC",
    mintAddress: "J9BcrQfX4p9D1bvLzRNCbMDv8f44a9LFdeqNE4Yk2WMD",
    decimals: 6,
    image: "/assets/svg/stablecoins/isc.svg",
    status: "available",
  },
  {
    name: "GYEN",
    mintAddress: "Crn4x1Y2HUKko7ox2EZMT6N2t2ZyH7eKtwkBGVnhEq1g",
    decimals: 6,
    image: "/assets/svg/stablecoins/gyen.svg",
    status: "available",
  },
  {
    name: "NGNC",
    mintAddress: "BwaXCdG2hsW2PTieBc14Ys92yKVGWSQSATY9juwkBEZo",
    decimals: 9,
    image: "/assets/svg/stablecoins/ngnc.svg",
    status: "unavailable",
  },
  {
    name: "ZARP",
    mintAddress: "8v8aBHR7EXFZDwaqaRjAStEcmCj6VZi5iGq1YDtyTok6",
    decimals: 6,
    image: "/assets/svg/stablecoins/zarp.svg",
    status: "unavailable",
  },
  {
    name: "MXNe",
    mintAddress: "6zYgzrT7X2wi9a9NeMtUvUWLLmf2a8vBsbYkocYdB9wa",
    decimals: 9,
    image: "/assets/svg/stablecoins/mxne.svg",
    status: "unavailable",
  },
  {
    name: "VEUR",
    mintAddress: "C4Kkr9NZU3VbyedcgutU6LKmi6MKz81sx6gRmk5pX519",
    decimals: 9,
    image: "/assets/svg/stablecoins/veur.svg",
    status: "available",
  },
  {
    name: "VCHF",
    mintAddress: "AhhdRu5YZdjVkKR3wbnUDaymVQL2ucjMQ63sZ3LFHsch",
    decimals: 9,
    image: "/assets/svg/stablecoins/vchf.svg",
    status: "available",
  },
];
