export const Tokens = [
  {
    name: "EUROe",
    mintAddress: '2VhjJ9WxaGC3EZFwJG9BDUs9KxKCAjQY4vgd1qxgYWVg',
    decimals: 6,
    image: "/assets/svg/stablecoins/euroe.svg",
  },
  {
    name: "QCAD",
    decimals: 2,    
    mintAddress: 'EeBX9JLdvsp4HnBbMgC1HnAjBkBQxgxtWxspcCLtT6ci',
    image: "/assets/svg/stablecoins/qcad.svg",
  },
  {
    name: "USDC",
    mintAddress: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
    decimals: 6,
    image: "/assets/svg/stablecoins/usdc.svg",
  },
  {
    name: "USDY",
    mintAddress: 'CfU2HYTfpkQrWHKerRV7fzk5bquoMp1tBjdxAU63pump',
    decimals: 6,
    image: "/assets/svg/stablecoins/usdy.svg",
  },
  {
    name: "USDT",
    mintAddress: 'Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB',    
    decimals: 6,
    image: "/assets/svg/stablecoins/usdt.svg",
  },
  {
    name: "PYUSD",
    mintAddress: '2b1kV6DkPAnxd5ixfnxCpjxmKwqjjaYmCZfHsFu24GXo',    
    decimals: 6,
    image: "/assets/svg/stablecoins/pyusd.svg",
  },
  {
    name: "BRZ",
    mintAddress: 'DKjNwdTK2zW1412rWpU5xKkMexingV244122Nj2apump',    
    decimals: 6,
    image: "/assets/svg/stablecoins/brz.svg",
  },
  {
    name: "EURC",
    mintAddress: 'BnVsBynMZEijPPJ9iYjVaG4sgTKgMBXjikCEFxhepump',
    decimals: 6,
    image: "/assets/svg/stablecoins/eurc.svg",
  },
  {
    name: "TRYB",
    mintAddress: '6ry4WBDvAwAnrYJVv6MCog4J8zx6S3cPgSqnTsDZ73AR',    
    decimals: 6,
    image: "/assets/svg/stablecoins/tryb.svg",
  },
  {
    name: "ISC",
    mintAddress: '9C7GgKdcz7HxmTNXUNZDgjgbKZ1b7ePEYzLb7y8cpump',
    decimals: 6,
    image: "/assets/svg/stablecoins/isc.svg",
  },
  {
    name: "GYEN",
    mintAddress: 'A5x6VtX6QCHJ5NH9fNN2xXk9d9Df71KfMTs2oMMf9HhU',
    decimals: 8,
    image: "/assets/svg/stablecoins/gyen.svg",
  },
  {
    name: "NGNC",
    mintAddress: 'BwaXCdG2hsW2PTieBc14Ys92yKVGWSQSATY9juwkBEZo',
    decimals: 9,
    image: "/assets/svg/stablecoins/ngnc.svg",
  },
  {
    name: "ZARP",
    mintAddress: '8v8aBHR7EXFZDwaqaRjAStEcmCj6VZi5iGq1YDtyTok6',
    decimals: 6,
    image: "/assets/svg/stablecoins/zarp.svg",
  },
  {
    name: "MXNe",
    mintAddress: '6zYgzrT7X2wi9a9NeMtUvUWLLmf2a8vBsbYkocYdB9wa',
    decimals: 9,
    image: "/assets/svg/stablecoins/mxne.svg",
  },
  {
    name: "VEUR",
    mintAddress: 'C4Kkr9NZU3VbyedcgutU6LKmi6MKz81sx6gRmk5pX519',
    decimals: 9,
    image: "/assets/svg/stablecoins/veur.svg",
  },
  {
    name: "VCHF",
    mintAddress: 'AhhdRu5YZdjVkKR3wbnUDaymVQL2ucjMQ63sZ3LFHsch',
    decimals: 9,
    image: "/assets/svg/stablecoins/vchf.svg",
  },
];
