// export const Tokens = [
//   {
//     name: "cEUR",
//     decimals: 18,
//     mintAddress: "0xD8763CBa276a3738E6DE85b4b3bF5FDed6D6cA73",
//     image: "/assets/svg/stables/ceur.svg",
//     status: "available",
//   },
//   {
//     name: "cREAL",
//     decimals: 18,
//     mintAddress: "0xe8537a3d056DA446677B9E9d6c5dB704EaAb4787",
//     image: "/assets/svg/stables/creal.svg",
//     status: "available",
//   },
//   {
//     name: "cKES",
//     mintAddress: "0x456a3D042C0DbD3db53D5489e98dFb038553B0d0",
//     decimals: 18,
//     image: "/assets/svg/stables/ckes.svg",
//     status: "available",
//   },
//   {
//     name: "eXOF",
//     mintAddress: "0x73F93dcc49cB8A239e2032663e9475dd5ef29A08",
//     decimals: 18,
//     image: "/assets/svg/stables/exof.svg",
//     status: "available",
//   },
//   {
//     name: "cUSD",
//     mintAddress: "0x765DE816845861e75A25fCA122bb6898B8B1282a",
//     decimals: 18,
//     image: "/assets/svg/stables/cusd.svg",
//     status: "available",
//   },
//   {
//     name: "PUSO",
//     mintAddress: "0x105d4A9306D2E55a71d2Eb95B81553AE1dC20d7B",
//     decimals: 18,
//     image: "/assets/svg/stables/puso.svg",
//     status: "available",
//   },
//   {
//     name: "USDC",
//     mintAddress: "0xcebA9300f2b948710d2653dD7B07f33A8B32118C",
//     decimals: 6,
//     image: "/assets/svg/stables/usdc.svg",
//     status: "available",
//   },
//   {
//     name: "USDT",
//     mintAddress: "0x48065fbBE25f71C9282ddf5e1cD6D6A887483D5e",
//     decimals: 6,
//     image: "/assets/svg/stables/usdt.svg",
//     status: "available",
//   },
// ];

export const Networks = [
  {
    id: 1,
    name: "Solana",
    label: "Solana",
    flag: "/assets/svg/networks/solana.svg",
  },
  {
    id: 2,
    name: "Celo",
    label: "Celo",
    chainId: 42220,
    flag: "/assets/svg/networks/celo.svg",
  },
  {
    id: 3,
    name: "Base",
    label: "Base",
    chainId: 8543,
    flag: "/assets/svg/networks/base.svg",
  },
];

export const Tokens = [
  {
    id: 1,
    network: "Solana",
    stables: [
      {
        name: "BRZ",
        mintAddress: "FtgGSFADXBtroxq8VCausXRr2of47QBf5AS1NtZCu4GD",
        decimals: 4,
        image: "/assets/svg/stablecoins/brz.svg",
        status: "available",
      },
      {
        name: "EURC",
        mintAddress: "HzwqbKZw8HxMN6bF2yFZNrht3c2iXXzpKcFu7uBEDKtr",
        decimals: 6,
        image: "/assets/svg/stablecoins/eurc.svg",
        status: "available",
      },
      // {
      //   name: "GYEN",
      //   mintAddress: "Crn4x1Y2HUKko7ox2EZMT6N2t2ZyH7eKtwkBGVnhEq1g",
      //   decimals: 6,
      //   image: "/assets/svg/stablecoins/gyen.svg",
      //   status: "available",
      // },
      // {
      //   name: "ISC",
      //   mintAddress: "J9BcrQfX4p9D1bvLzRNCbMDv8f44a9LFdeqNE4Yk2WMD",
      //   decimals: 6,
      //   image: "/assets/svg/stablecoins/isc.svg",
      //   status: "available",
      // },
      // {
      //   name: "MXNE",
      //   mintAddress: "6zYgzrT7X2wi9a9NeMtUvUWLLmf2a8vBsbYkocYdB9wa",
      //   decimals: 9,
      //   image: "/assets/svg/stablecoins/mxne.svg",
      //   status: "available",
      // },
      // {
      //   name: "NGNC",
      //   mintAddress: "BwaXCdG2hsW2PTieBc14Ys92yKVGWSQSATY9juwkBEZo",
      //   decimals: 9,
      //   image: "/assets/svg/stablecoins/ngnc.svg",
      //   status: "unavailable",
      // },
      {
        name: "PYUSD",
        mintAddress: "2b1kV6DkPAnxd5ixfnxCpjxmKwqjjaYmCZfHsFu24GXo",
        decimals: 6,
        image: "/assets/svg/stablecoins/pyusd.svg",
        status: "available",
      },
      {
        name: "QCAD",
        decimals: 2,
        mintAddress: "EeBX9JLdvsp4HnBbMgC1HnAjBkBQxgxtWxspcCLtT6ci",
        image: "/assets/svg/stablecoins/qcad.svg",
        status: "available",
      },
      // {
      //   name: "TRYB",
      //   mintAddress: "6ry4WBDvAwAnrYJVv6MCog4J8zx6S3cPgSqnTsDZ73AR",
      //   decimals: 6,
      //   image: "/assets/svg/stablecoins/tryb.svg",
      //   status: "unavailable",
      // },
      {
        name: "USDC",
        mintAddress: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
        decimals: 6,
        image: "/assets/svg/stablecoins/usdc.svg",
        status: "available",
      },
      {
        name: "USDT",
        mintAddress: "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB",
        decimals: 6,
        image: "/assets/svg/stablecoins/usdt.svg",
        status: "available",
      },
      // {
      //   name: "VCHF",
      //   mintAddress: "AhhdRu5YZdjVkKR3wbnUDaymVQL2ucjMQ63sZ3LFHsch",
      //   decimals: 9,
      //   image: "/assets/svg/stablecoins/vchf.svg",
      //   status: "available",
      // },
      // {
      //   name: "VEUR",
      //   mintAddress: "C4Kkr9NZU3VbyedcgutU6LKmi6MKz81sx6gRmk5pX519",
      //   decimals: 9,
      //   image: "/assets/svg/stablecoins/veur.svg",
      //   status: "available",
      // },
      {
        name: "ZARP",
        mintAddress: "8v8aBHR7EXFZDwaqaRjAStEcmCj6VZi5iGq1YDtyTok6",
        decimals: 6,
        image: "/assets/svg/stablecoins/zarp.svg",
        status: "available",
      },
    ],
  },
  {
    id: 2,
    network: "Celo",
    stables: [
      {
        name: "cEUR",
        decimals: 18,
        mintAddress: "0xD8763CBa276a3738E6DE85b4b3bF5FDed6D6cA73",
        image: "/assets/svg/stables/ceur.svg",
        status: "available",
      },
      {
        name: "cREAL",
        decimals: 18,
        mintAddress: "0xe8537a3d056DA446677B9E9d6c5dB704EaAb4787",
        image: "/assets/svg/stables/creal.svg",
        status: "available",
      },
      // {
      //   name: "cKES",
      //   mintAddress: "0x456a3D042C0DbD3db53D5489e98dFb038553B0d0",
      //   decimals: 18,
      //   image: "/assets/svg/stables/ckes.svg",
      //   status: "available",
      // },
      // {
      //   name: "eXOF",
      //   mintAddress: "0x73F93dcc49cB8A239e2032663e9475dd5ef29A08",
      //   decimals: 18,
      //   image: "/assets/svg/stables/exof.svg",
      //   status: "available",
      // },
      {
        name: "cUSD",
        mintAddress: "0x765DE816845861e75A25fCA122bb6898B8B1282a",
        decimals: 18,
        image: "/assets/svg/stables/cusd.svg",
        status: "available",
      },
      {
        name: "PUSO",
        mintAddress: "0x105d4A9306D2E55a71d2Eb95B81553AE1dC20d7B",
        decimals: 18,
        image: "/assets/svg/stables/puso.svg",
        status: "available",
      },
      {
        name: "USDC",
        mintAddress: "0xcebA9300f2b948710d2653dD7B07f33A8B32118C",
        decimals: 6,
        image: "/assets/svg/stables/usdc.svg",
        status: "available",
      },
      {
        name: "USDT",
        mintAddress: "0x48065fbBE25f71C9282ddf5e1cD6D6A887483D5e",
        decimals: 6,
        image: "/assets/svg/stables/usdt.svg",
        status: "available",
      },
    ],
  },
  {
    id: 3,
    network: "Base",
    stables: [
      {
        name: "USDC",
        mintAddress: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
        decimals: 6,
        image: "/assets/svg/stables/usdc.svg",
        status: "available",
      },
      {
        name: "EURC",
        mintAddress: "0x60a3E35Cc302bFA44Cb288Bc5a4F316Fdb1adb42",
        decimals: 6,
        image: "/assets/svg/stables/eurc.svg",
        status: "available",
      },
      {
        name: "BRZ",
        mintAddress: "0xE9185Ee218cae427aF7B9764A011bb89FeA761B4",
        decimals: 18,
        image: "/assets/svg/stables/brz.svg",
        status: "available",
      },
      {
        name: "CADC",
        mintAddress: "0x043eb4b75d0805c43d7c834902e335621983cf03",
        decimals: 18,
        image: "/assets/svg/stables/cadc.svg",
        status: "available",
      },
      {
        name: "IDRX",
        mintAddress: "0x18bc5bcc660cf2b9ce3cd51a404afe1a0cbd3c22",
        decimals: 2,
        image: "/assets/svg/stables/idrx.svg",
        status: "available",
      },
      {
        name: "MXNE",
        mintAddress: "0x269cae7dc59803e5c596c95756faeebb6030e0af",
        decimals: 6,
        image: "/assets/svg/stables/mxne.svg",
        status: "available",
      },
      {
        name: "TRYB",
        mintAddress: "0x18bc5bcc660cf2b9ce3cd51a404afe1a0cbd3c22",
        decimals: 6,
        image: "/assets/svg/stables/tryb.svg",
        status: "available",
      },
      {
        name: "ZARP",
        mintAddress: "0xb755506531786c8ac63b756bab1ac387bacb0c04",
        decimals: 18,
        image: "/assets/svg/stables/zarp.svg",
        status: "available",
      },
      {
        name: "NZDD",
        mintAddress: "0x2dd087589ce9c5b2d1b42e20d2519b3c8cf022b7",
        decimals: 6,
        image: "/assets/svg/stables/nzdd.svg",
        status: "unavailable",
      },
    ],
  },
];
